name: Jesse Stommel
favicon: null
layout_spectrum: 0.49433
typography_spectrum: 0.69578
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#222222'
    - '#2695e1'
    - '#65b4ea'
    - '#cccccc'
    - '#777777'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
